# Generated by Django 2.2.2 on 2019-06-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cached_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=None, max_length=255, unique=True)),
                ('image_file', models.ImageField(default='defaults/default.png', upload_to='cached_images')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
