# Generated by Django 2.2.2 on 2019-07-02 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cached_Gallery',
            fields=[
                ('place_id', models.CharField(default=None, max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='cached_image',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cached_image',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='cached_image',
            name='reference',
            field=models.CharField(default=None, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='cached_image',
            name='gallery',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Cached_Gallery'),
        ),
    ]
