# Generated by Django 2.2.1 on 2019-05-18 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TEST',
            new_name='TEST_TEST',
        ),
    ]
