# Generated by Django 2.2.2 on 2019-07-02 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190702_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cached_image',
            name='gallery',
        ),
        migrations.DeleteModel(
            name='Cached_Gallery',
        ),
        migrations.DeleteModel(
            name='Cached_Image',
        ),
    ]
