# Generated by Django 2.2.1 on 2019-05-18 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190518_1709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cached_Image',
        ),
    ]
