# Generated by Django 2.2.1 on 2019-05-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0004_delete_cached_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cached_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_reference', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('miniature', models.ImageField(default='defaults/default.png', upload_to='cached_images')),
            ],
        ),
    ]
