# Generated by Django 2.2.2 on 2019-07-02 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cached_gallery_cached_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cached_Gallery',
            new_name='Cached_Details',
        ),
    ]
