# Generated by Django 2.2.1 on 2019-05-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cached_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cached_image',
            name='photo_reference',
            field=models.CharField(max_length=500),
        ),
    ]
