# Generated by Django 2.2.1 on 2019-05-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190518_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cached_image',
            old_name='miniature',
            new_name='image',
        ),
    ]
