# Generated by Django 2.2.2 on 2019-07-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0006_auto_20190702_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cached_Image',
            fields=[
                ('reference', models.CharField(default=None, max_length=255, primary_key=True, serialize=False)),
                ('image_file', models.ImageField(default='defaults/default.png', upload_to='cached_images')),
            ],
        ),
    ]
