# Generated by Django 2.2.2 on 2019-07-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cached_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cached_image',
            name='height',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='cached_image',
            name='width',
            field=models.IntegerField(default=100),
        ),
    ]
