# Generated by Django 2.2.1 on 2019-05-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190518_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cached_image',
            old_name='image',
            new_name='image_file',
        ),
        migrations.RemoveField(
            model_name='cached_image',
            name='photo_reference',
        ),
        migrations.AddField(
            model_name='cached_image',
            name='image_url',
            field=models.CharField(default=None, max_length=600),
            preserve_default=False,
        ),
    ]
