# Generated by Django 2.2.1 on 2019-05-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190519_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cached_image',
            name='image_url',
            field=models.CharField(default='defualt for test', max_length=600),
        ),
    ]
