# Generated by Django 2.2.2 on 2019-07-17 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190714_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cached_image',
            name='height',
        ),
        migrations.RemoveField(
            model_name='cached_image',
            name='width',
        ),
    ]
